name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: resolute
          ROS_DISTRO: lyrical
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SBUILD_CONF: "$enable_network = 1;"
